export const listaTypes = {
  GET_LISTA: "GET_LISTA",
  GET_LISTA_ERROR: "GET_LISTA_ERROR",
  LOADING_LISTA: "LOADING_LISTA"
};

export const extratoTypes = {
  GET_EXTRATO: "GET_EXTRATO",
  GET_EXTRATO_ERROR: "GET_EXTRATO_ERROR",
  LOADING_EXTRATO: "LOADING_EXTRATO"
};
